services:

  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - nexfila-network

  frontend:
    build: ../nexfila-frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - nexfila-network

networks:
  nexfila-network:
    driver: bridge